### PR TITLE
Allow using DSPy with Python 3.12

### LINKED ISSUE #572: Support python 3.12
Python 3.12 has significant improvements for asyncio: https://docs.python.org/3/whatsnew/3.12.html

"The [asyncio](https://docs.python.org/3/library/asyncio.html#module-asyncio) package has had a number of performance improvements, with some benchmarks showing a 75% speed up."

I know dspy doesn't support asyncio yet but given the discussions around supporting it, it's worth supporting 3.12.

From doing this on a branch, seems like the one missing dependency is onnx, which recently added support for 3.12 and will support it officially with their 1.16 release: https://github.com/onnx/onnx/issues/5884

### PR DESCRIPTION
**Pull request by krishnan-chandra**
Closes #572.

Hello! We use DSPy with Python 3.12 in production and would be happy to contribute this support back to the project if desired.

In terms of the changes required to get this working, there were only two:

1. Bump the Python version in `pyproject.toml`.
2. Upgrade the `fastembed` package to at least version `0.2.0`.

I see that this has already been looked at in  #582 but I'm not sure what the status of that PR is at this point.

### CODE REVIEW

**Comment by dentro-innovation** [comment]
Would highly appreciate enabling python3.12 🙏

**Comment by arnavsinghvi11** [comment]
Hi @krishnan-chandra , thanks for the PR! 

I think this can be merged but tagging @hmoazam here since this impacts dependencies and an existing PR #919 related to ensuring proper pypi/dependency releases. Let us know if this is fine to merge or should wait for your PR @hmoazam !

**Comment by hmoazam** [comment]
> Hi @krishnan-chandra , thanks for the PR!
> 
> I think this can be merged but tagging @hmoazam here since this impacts dependencies and an existing PR #919 related to ensuring proper pypi/dependency releases. Let us know if this is fine to merge or should wait for your PR @hmoazam !

This looks fine to me, I should have my PR in tomorrow and can merge in these changes so not a problem.

**Comment by arnavsinghvi11** [comment]
Thanks everyone!

**Pull request merged**
