### PR TITLE
documentation and QuizGen+TweetGen notebooks

### PR DESCRIPTION
**Pull request by arnavsinghvi11**
-documentation for DSPy Assertions
-example notebooks for the QuizGen and TweetGen tasks

### CODE REVIEW

**Comment by arnavsinghvi11** [comment]
WIP currently since Compile+Infer strategy is running into caching errors due to some recent changes. will merge once this is resolved.

**Comment by okhat** [comment]
Maybe mark as "draft" if still WIP

**Comment by okhat** [comment]
Btw cache problems, are they due to openai version? 0.28.1 vs 1.16

**Comment by Shangyint** [comment]
The issue might be due to multithreading in compiling. Needs to investigate further, but as for the cached notebook, it is fine to use one thread for `compile`, which solves the current issue.

**Pull request merged**
