### PR TITLE
Adds native support for Claude models

### PR DESCRIPTION
**Pull request by skucherlapati**
Adds native support for claude wrapper

### CODE REVIEW

**Comment by insop** [comment]
Thank you.

It would be great if this files is updated, `setup.py` for package requirement
Also it would good to add the documentation in this folder: `docs/api/language_model_clients`

**Comment by okhat** [comment]
Thanks a lot! No don't update setup.py, this does not need to be a global requirement.

Instead the import should happen only if needed, e.g. inside __init___

**Comment by CShorten** [comment]
@insop could you please help me with the ruff check here? I tried with:

```
ruff check . --fix-only
```

**Comment by insop** [comment]
> @insop could you please help me with the ruff check here? I tried with:
> 
> ```
> ruff check . --fix-only
> ```

I am new to `ruff` as I am still use `black`.

But I gave it a try by merging this PR branch to current main a51aad7dcbe257e01d677025cad96acba7c13e90.

Here is what I found:
- main branch a51aad7dcbe257e01d677025cad96acba7c13e90: no ruff issue
- my test branch with this PR merged to main: has many ruff issues that are not part of the PR
(I double checked my test merging branch)

It is appeared to be that there is some config file change or some type of cached information are playing here?

Sorry, I tried, not no answer to this.

**Comment by CShorten** [comment]
Ok, so good to merge this PR without passing the ruff test?

Lgtm otherwise, maybe before every release we run the ruff test on master until this is fully understood within the team going forward?

**Comment by isaacbmiller** [comment]
Looking into this now. Do not merge yet, the test failing is not CI fault

**Comment by isaacbmiller** [comment]
@CShorten How are you pushing to this pull request?

**Comment by isaacbmiller** [comment]
Sorry for messing with your branch. Going to move to another test PR to work on this

**Comment by isaacbmiller** [comment]
Okay I fixed the issues:
1. You need to make the imports optional, as anthropic is not a required dependency. That is why the tests were failing
2. Somehow, there was a deletion of a Ruff rule in `pyproject.toml`, which is where there were so many fixes.
Sorry for the mess on your branch!

Good to merge whenever @okhat @CShorten

**Comment by CShorten** [comment]
Hey @insop this looks resolved! Please update me otherwise!

Yeah also not sure 100% how I was able to directly commit to @skucherlapati's repo, I think because of dspy permissions.

**Comment by CShorten** [comment]
Thank you so much @insop !! Really appreciate your contribution to this! Claude API in DSPy!! Super cool!

**Comment by insop** [comment]
> Thank you so much @insop !! Really appreciate your contribution to this! Claude API in DSPy!! Super cool!

Thank you @CShorten, happy to see Claude API in DSPy as well.

**Comment by skucherlapati** [comment]
Thanks for the help on getting this merged. Makes sense - I should have made it optional!

**Pull request merged**
