### PR TITLE
Add ChatBackend and TextBackend enhancements

### PR DESCRIPTION
**Pull request by Neoxelox**
Adds ChatBackend and fixes some things in TextBackend

### CODE REVIEW

**Comment by arnavsinghvi11** [comment]
is this PR potentially overlapping with the existing [WIP Backend Refactor](https://github.com/stanfordnlp/dspy/pull/424)?

@CyrusOfEden @KCaverly

**Comment by CyrusOfEden** [comment]
No actually building upon it! Cool to see. 

Btw why reconstruct the entire prompt and extract? Was that the simplest way?

**Comment by Neoxelox** [comment]
> No actually building upon it! Cool to see.
> 
> Btw why reconstruct the entire prompt and extract? Was that the simplest way?

I didn't fully understand what were some parts doing in the `_extract` function, so, yes that was the simples way.

**Comment by tom-doerr** [comment]
This probably solves https://github.com/stanfordnlp/dspy/issues/977

**Comment by canada4663** [comment]
Any idea if this will merge and is a good base for building around?

**Comment by CyrusOfEden** [comment]
Awesome stuff!

**Pull request merged**
