### PR TITLE
Add Custom Rationale Type option in TypedChainOfThought Module

### PR DESCRIPTION
**Pull request by krypticmouse**
Add an argument for custom rationale type like:

```python
        rationale_type = dsp.Type(
            prefix="Take a deep breath and let's think step by step in order...",
            desc="Based on the context...",
        )

        self.task = dspy.TypedChainOfThought(SomeTask, rationale_type=rationale_type)
```

### CODE REVIEW

**Review by Josephrp — COMMENTED** [review]
is this change required ?

**Comment by Josephrp** [comment]
> Thought it might come handy 🤔

yeah absolutely handy, had not noted my previous review of the main changes , so that's why i made that comment - with all my appologies  ! i'm actually testing it out , because i'm in the same situation , trying out stuff and building demos :-)

**Comment by krypticmouse** [comment]
No worries at all!! Thanks for the comment!!!

**Comment by thomasahle** [comment]
Technical question: Can you prepend a dsp.Type to dspy.Signature? I'm pretty sure you can only prepend dspy.Fields, no?

Practical question: The TypedChainOfThought function is already doing very little work (just one call to signature.prepend). Why not just add the alternative field to the signature yourself, and then use TypedPredictor?

**Comment by krypticmouse** [comment]
> Can you prepend a dsp.Type to dspy.Signature? I'm pretty sure you can only prepend dspy.Fields, no?
 
 You can't prepend dsp.Type ig. But the rationale_type being dsp.Type is deprecated now and is replace with dspy.OutputField overall.
 
 > The TypedChainOfThought function is already doing very little work (just one call to signature.prepend). Why not just add the alternative field to the signature yourself, and then use TypedPredictor?
 
 Good point. I think that'll reduce the friction of migrating away from `ChainOfThought` to `TypedChainOfThought`. I agree there is not much that is happening but I think this sort of functionality being native will reduce the burden on user "to do something" on their end.

**Comment by arnavsinghvi11** [comment]
Thanks @krypticmouse ! Is this good to merge? LGTM, but checking if anything was left

**Comment by thomasahle** [comment]
>  think that'll reduce the friction of migrating away from ChainOfThought to TypedChainOfThought.  

Ok, fair enough.

But can we at least rename it to `rationale_field`, since it's no longer a dsp.Type?

Oe maybe `reasoning_field`, since we are no longer calling the field rationale. So if people want to get the output value, they need to check output reasoning.

Or maybe just `reasoning` since we don't normally add the type of a variable to the name?

**Comment by krypticmouse** [comment]
Yes we can! Wrote that just to keep the convention same, lemme edit it out and merge!

**Pull request merged**
