### PR TITLE
Deep dive teleprompter rename

### PR DESCRIPTION
**Pull request by tom-doerr**
I keep getting confused when I search for information on optimizers and can't find it since some sections are still named teleprompters. I just went ahead and refactored the deep dive section. I hope you don't mind!

### CODE REVIEW

**Comment by arnavsinghvi11** [comment]
Hi @tom-doerr , thanks for this change! This has been long overdue but we will also need to do this refactoring within the repository to align with Optimizers overall. @okhat is this a good time to make this transition?

**Comment by tom-doerr** [comment]
If it's basically just renaming teleprompt to optimize and adding deprecation warnings if someone continues to use teleprompt I could try to add it to the PR

**Comment by tom-doerr** [comment]
Adding deprecation warnings while keeping it functional seems straightforward. 
`dspy/teleprompt/teleprompt.py` would become:
```
import warnings
warnings.warn(
    "The 'teleprompt' module has been renamed to 'optimize'. Please update your imports.",
    DeprecationWarning
)
from dspy.optimize.optimize import *
```

Would be happy to help out with refactoring.

**Comment by tom-doerr** [comment]
Ah okay, `LabeledFewShot` is probably also not an optimizer

**Pull request closed without merging**
