### PR TITLE
Update BootstrapFewShot docs

### PR DESCRIPTION
**Pull request by karthikscale3**
Minor updates to the BootstrapFewShot docs with the goal of improving the clarity.

### CODE REVIEW

**Comment by okhat** [comment]
Hey @karthikscale3 , looks good to me but seems like we have conflicts unfortunately.

**Comment by krypticmouse** [comment]
@karthikscale3 we've migrated from docusaurus to mkdocs, can you adopt these changes to it?

P.S. these files are in a new folder now.

**Comment by karthikscale3** [comment]
@krypticmouse and @okhat - Thanks for the review. I wasn't aware of the docs migration. But, no worries, I will adapt to the new stuff and update the PR.

**Comment by krypticmouse** [comment]
Yea it was pretty recent, sorry about the silent migration. Thank you so much for the contribution!

**Comment by karthikscale3** [comment]
@krypticmouse / @okhat - Closing this PR. I have opened a new one that updates the new docs file. https://github.com/stanfordnlp/dspy/pull/1674

**Pull request closed without merging**
