### PR TITLE
KNN few shot fixes

### PR DESCRIPTION
**Pull request by adam-simple**
- Don't pass valset to bootstrap fewshot
- forward_pass unpacks appropriately
- few shot bootstrap args to pass through during forward pass

### CODE REVIEW

**Comment by adam-simple** [comment]
It might make sense to put a warning in the KNN call if **kwargs is empty. this can easily happen if someone calls .forward without keyword arguments, instead using args without keywords, like module.forward(input) or something

**Comment by okhat** [comment]
Thanks! Probably remove `*args` altogether then?

**Comment by okhat** [comment]
tagging @adam-simple

**Comment by adam-simple** [comment]
done

**Comment by arnavsinghvi11** [comment]
Thanks @adam-simple !

**Pull request merged**
