### PR TITLE
Updated docs to MIPRO and COPRO

### PR DESCRIPTION
**Pull request by XenonMolecule**
SignatureOptimizer names are deprecated

### CODE REVIEW

**Comment by XenonMolecule** [comment]
@arnavsinghvi11 I haven't done work on the doc side as much.  Can you confirm that this does all the necessary steps to update [this page](https://dspy-docs.vercel.app/docs/building-blocks/optimizers) or will I need to build anything separately?

**Comment by arnavsinghvi11** [comment]
Thanks @XenonMolecule ! Once the PR is merged, I'll update the docs on the landing page. 

Just wanted to highlight some of the other mentions of SignatureOptimizers in case you wanted to update these as well to match MIPRO and COPRO (Hope its not too many!)


- https://github.com/stanfordnlp/dspy/blob/aa55b2e54798265dfe8d42f31ca7d6230310c7de/docs/docs/cheatsheet.md?plain=1#L359
- https://github.com/stanfordnlp/dspy/blob/aa55b2e54798265dfe8d42f31ca7d6230310c7de/docs/docs/deep-dive/teleprompter/signature-optimizer.mdx#L9
-https://github.com/stanfordnlp/dspy/blob/aa55b2e54798265dfe8d42f31ca7d6230310c7de/docs/docs/building-blocks/2-signatures.md?plain=1#L106
-https://github.com/stanfordnlp/dspy/blob/aa55b2e54798265dfe8d42f31ca7d6230310c7de/docs/docs/intro.md?plain=1#L18
-https://github.com/stanfordnlp/dspy/blob/aa55b2e54798265dfe8d42f31ca7d6230310c7de/docs/docs/building-blocks/solving_your_task.md?plain=1#L92

**Comment by XenonMolecule** [comment]
Thanks @arnavsinghvi11, I updated these as well now!

**Comment by arnavsinghvi11** [comment]
Thanks @XenonMolecule !

**Pull request merged**
