### PR TITLE
Fix return_all_scores in evaluate

### PR DESCRIPTION
**Pull request by quajak**
Addresses https://github.com/stanfordnlp/dspy/issues/477

### CODE REVIEW

**Comment by arnavsinghvi11** [comment]
Thanks @quajak !

@isaacbmiller similar tag here as the PR is failing checks

**Comment by quajak** [comment]
Hi, not sure why the checks are failing with the current error.

**Comment by isaacbmiller** [comment]
This is blocked until #565 is merged. I will have time to finish 565 tomorrow/thursday.

This is only not passing because it comes from a fork instead of the main repo. @quajak if you are okay with not being the author/need this asap (I want you to get the contribution!) I can make a branch.

**Comment by quajak** [comment]
I see. Thank you for the explanation. The PR is not urgent, so you can wait with merging until #565 is done.

**Comment by quajak** [comment]
The changes seem to have been reverted by https://github.com/stanfordnlp/dspy/pull/565/commits/e659fc2c001dc4461a931f43a7a070bc17157a6a as part of https://github.com/stanfordnlp/dspy/pull/565 . Was this intentional?

**Comment by isaacbmiller** [comment]
I merged and reverted to check if CI would pass, but I still wanted you to merge yours after

**Comment by quajak** [comment]
I see, should I make a new PR with the changes?

**Comment by isaacbmiller** [comment]
Weird. I guess so @quajak. Tag me and I will merge it

**Pull request merged**
