### PR TITLE
Allow HFModel to use CPU

### PR DESCRIPTION
**Pull request by tisu19021997**
Quick fix https://github.com/stanfordnlp/dspy/issues/188

I think this minor fix could be very helpful for Mac beginners as well as CPU beginners who just get started using the library.

### CODE REVIEW

**Comment by insop** [comment]
The change looks good to me.
One thought is that it would been easier for whoever reads the PR if the changes only the fixes instead other changes such as coding style changes.

**Comment by tisu19021997** [comment]
@insop thanks. I just reverted the coding style changes.

**Comment by insop** [comment]
> @insop thanks. I just reverted the coding style changes.

Looks great to me! thank you.

**Comment by insop** [comment]
@okhat , maybe you could merge if you are okay with the change?

**Comment by okhat** [comment]
Merging but please prefer ollama over hfmodel when possible

**Pull request merged**
