### PR TITLE
hotfix(dsp): In HFClientVLLM get the model from the kwargs attached by the parent class

### LINKED ISSUE #764: AttributeError: 'HFClientVLLM' object has no attribute 'model'
```
AttributeError                            Traceback (most recent call last)
File <command-1178964926776796>, line 3
      1 import dspy
      2 lm = dspy.HFClientVLLM(model="mistralai/Mistral-7B-Instruct-v0.2", port=8000, url="http://0.0.0.0/")
----> 3 lm("My name is Robert")

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-9dfc2a8f-024c-4b74-a13e-e541ebac4e5c/lib/python3.10/site-packages/dsp/modules/hf.py:183, in HFModel.__call__(self, prompt, only_completed, return_sorted, **kwargs)
    180 if kwargs.get("n", 1) > 1 or kwargs.get("temperature", 0.0) > 0.1:
    181     kwargs["do_sample"] = True
--> 183 response = self.request(prompt, **kwargs)
    184 return [c["text"] for c in response["choices"]]

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-9dfc2a8f-024c-4b74-a13e-e541ebac4e5c/lib/python3.10/site-packages/dsp/modules/lm.py:26, in LM.request(self, prompt, **kwargs)
     25 def request(self, prompt, **kwargs):
---> 26     return self.basic_request(prompt, **kwargs)

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-9dfc2a8f-024c-4b74-a13e-e541ebac4e5c/lib/python3.10/site-packages/dsp/modules/hf.py:140, in HFModel.basic_request(self, prompt, **kwargs)
    138 raw_kwargs = kwargs
    139 kwargs = {**self.kwargs, **kwargs}
--> 140 response = self._generate(prompt, **kwargs)
    142 history = {
    143     "prompt": prompt,
    144     "response": response,
    145     "kwargs": kwargs,
    146     "raw_kwargs": raw_kwargs,
    147 }
    148 self.history.append(history)

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-9dfc2a8f-024c-4b74-a13e-e541ebac4e5c/lib/python3.10/site-packages/dsp/modules/hf_client.py:137, in HFClientVLLM._generate(self, prompt, **kwargs)
    133 def _generate(self, prompt, **kwargs):
    134     kwargs = {**self.kwargs, **kwargs}
    136     payload = {
--> 137         "model": self.model,
    138         "prompt": prompt,
    139         **kwargs,
    140     }
    143     # Round robin the urls.
    144     url = self.urls.pop(0)

AttributeError: 'HFClientVLLM' object has no attribute 'model'
```

should be fixed by https://github.com/stanfordnlp/dspy/pull/762

### PR DESCRIPTION
**Pull request by remiconnesson**
In HFClientVLLM attach the model string directly to instance

Fixes an error in https://github.com/stanfordnlp/dspy/pull/719

Closes #764

### CODE REVIEW

**Comment by ammirsm** [comment]
LGTM and seems like it has been tested in the comment refrenced, I think it should be merged as hotfix, @arnavsinghvi11 can you please prioritize this one?

**Comment by manjubsavanth** [comment]
@arnavsinghvi11 topping up on the request from @ammirsm , please merge this on priority.

**Comment by manjubsavanth** [comment]
hi @arnavsinghvi11 I still get the below error, can you please test this before commiting the code?

```
File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/dsp/modules/hf_client.py:138, in HFClientVLLM._generate(self, prompt, **kwargs)
    133 def _generate(self, prompt, **kwargs):
    134     kwargs = {**self.kwargs, **kwargs}
    136     payload = {
    137         # "model": self.model,
--> 138         "model": kwargs["model"],
    139         "prompt": prompt,
    140         **kwargs,
    141     }
    144     # Round robin the urls.
    145     url = self.urls.pop(0)

KeyError: 'model'
```

**Comment by remiconnesson** [comment]
@manjubsavanth can you test if it works for you?

**Comment by remiconnesson** [comment]
One question remains:

the LM class sets some default arguments:
https://github.com/stanfordnlp/dspy/blob/fd63306642553ecb7d0916ea4156a374ae53c255/dsp/modules/lm.py#L4-L16

before #719 , only most of those were discarded
image

What do we want to do?

Right now (in this PR) we are using all the default kwargs values from the `LM` base class,

was there a reason for discarding most of the kwargs?

**Comment by remiconnesson** [comment]
@manjubsavanth can you tell if you notice a different behavior than before?

**Comment by manjubsavanth** [comment]
Hi @remiconnesson this works only with max_tokens and temperature, everything else does not work, for example in my case I need the top result like top_p=1 or n=1. which still does not seem to work.

**Comment by remiconnesson** [comment]
Can you show me how you are setting those params?

**Comment by manjubsavanth** [comment]
Here is the minimal code. 

```
import dspy
lm = dspy.HFClientVLLM(model="mistralai/Mistral-7B-Instruct-v0.2", port=8000, url="http://0.0.0.0")
dspy.settings.configure(lm=lm)

class FeedbackType(dspy.Signature):
    """Classify the given user feedback into Positive or Negative Sentiments"""
    text = dspy.InputField(desc= "Data to be classified")
    label = dspy.OutputField(desc="Falls in to one of the categories")

from dspy import (
    Signature,
    settings,
    context
)

text = "Software integration is seamless, making the workflow smooth"

pred_class = dspy.Predict(FeedbackType,temperature=0.00001,n=1,top_p=1,max_tokens=10)

with context(lm=lm):
    resp = pred_class(text=text)
    print("Mistral Response: ", resp.label)
```

**Comment by remiconnesson** [comment]
@manjubsavanth 

This fix is respecting n=1 what do you mean?
image

**Comment by remiconnesson** [comment]
I think vllm has early stopping

But more importantly is dspy adding the` [INST][/INST] ` Token on its own?  Maybe it's why it's struggling with following instructions

**Comment by manjubsavanth** [comment]
@remiconnesson Thanks a lot for the response. Given DSPy generates it's own prompts, is there a way to pass [INST][/INST] Token programmatically?

**Comment by remiconnesson** [comment]
> @remiconnesson Thanks a lot for the response. Given DSPy generates it's own prompts, is there a way to pass [INST][/INST] Token programmatically?

I don't know I've never used dspy yet as it was not firing my need with vllm

**Comment by manjubsavanth** [comment]
@arnavsinghvi11 8s this something that you are aware of?

**Comment by arnavsinghvi11** [comment]
@manjubsavanth including [INST] and other such chat templating is in the works with the backend refactor. #420 discusses some of this but at the moment, the chat templates are not integrated with DSPy yet. However, you can specify system prompts as needed.

**Comment by arnavsinghvi11** [comment]
@remiconnesson @ammirsm @manjubsavanth seems like the bug is fixed. Is the PR ready to merge?

**Comment by remiconnesson** [comment]
@arnavsinghvi11 yes I think so

**Comment by arnavsinghvi11** [comment]
Thanks everyone for the contributions and testing!

**Pull request merged**
