### PR TITLE
Llama CPP Support - Addressed some PR Comments - Extending 2 other PRs

### PR DESCRIPTION
**Pull request by AbdulDridi**
A continuation of these two:

https://github.com/stanfordnlp/dspy/pull/862

https://github.com/stanfordnlp/dspy/pull/1154

Addressing their pr comments

### CODE REVIEW

**Comment by arnavsinghvi11** [comment]
Thanks for carrying the LlamaCPP PR forward @AbdulDridi !

It's failing some of the [tests](https://github.com/stanfordnlp/dspy/actions/runs/10207843430/job/28245014846?pr=1347) due to the import error.

Could you instead move the try/except block to [inside the LlamaCPP init method](https://github.com/stanfordnlp/dspy/pull/1347/files#diff-c0d52589d87f25668240d9a7eaa5afa50a2cdd73e4ab77b16aa2c5d6ee5d26e1R26) so it only tries to import the library when dspy.LlamaCpp is being used?
You can then remove the addition of this optional poetry dependency in the `pyproject.toml` as well.

**Comment by AbdulDridi** [comment]
Updated

**Comment by arnavsinghvi11** [comment]
Thanks @AbdulDridi !

**Comment by shakfu** [comment]
@AbdulDridi 

Does this work with llama.cpp [server](https://github.com/ggerganov/llama.cpp/blob/master/examples/server/README.md) REST interface or does one have to install llama-cpp-python?

**Pull request merged**
