### PR TITLE
Catchup backend-refactor with main

### PR DESCRIPTION
**Pull request by KCaverly**
Merging main with backend-refactor to accomodate for new tests integrations and signatures.

### CODE REVIEW

**Comment by okhat** [comment]
Do we want to merge this now @KCaverly ? What are the pros/cons?

**Comment by okhat** [comment]
Especially because #424 is still a Draft

**Comment by KCaverly** [comment]
Sorry this should be merging to the backend refactor branch.

**Comment by okhat** [comment]
Ah got it. @KCaverly . Okay then I'll let @CyrusOfEden decide the right course of action

**Pull request closed without merging**
