### PR TITLE
Fix retreive typo

### PR DESCRIPTION
**Pull request by tom-doerr**

### CODE REVIEW

**Comment by krypticmouse** [comment]
@tom-doerr Can you try running `ruff check . --fix-only` to see if there is any issue?

**Comment by tom-doerr** [comment]
Can't imagine that the error is related to my PR, I only switched to letters in the docs. I can try this latter anyway if you want

**Comment by krypticmouse** [comment]
Thank You for the contribution!!

**Comment by krypticmouse** [comment]
Thank You for the contribution!!

**Pull request merged**
