### PR TITLE
ci(dspy): Add tests to CI

### LINKED ISSUE #456: Bug: Unable to run tests locally
Bug: Getting Unable to import dspy when trying to run the new tests

Steps to reproduce:
1. Clone main branch
2. python -m venv .env
3. source .env/bin/activate
4. pip install -r requirements.txt
5. pytest tests/predict/test_predict.py

Alternate steps to reproduce:
1. Clone main branch
2. poetry install
3. poetry shell
4. pytest tests/predict/test_predict.py

This throws a `ModuleNotFoundError: No module named 'dspy'`

Why does this matter? 
2 Reasons:
1. I was going to help Cyrus with part of the backend refactor, but can't test my code locally
2. We can't integrate the tests into CI

Full trace:
```
==================================================================================== test session starts ====================================================================================
platform darwin -- Python 3.11.4, pytest-7.4.0, pluggy-1.0.0
rootdir: /Users/isaac/Projects/dspy
plugins: anyio-3.5.0
collected 0 items / 1 error                                                                                                                                                                 

========================================================================================== ERRORS ===========================================================================================
______________________________________________________________________ ERROR collecting tests/predict/test_predict.py _______________________________________________________________________
ImportError while importing test module '/Users/isaac/Projects/dspy/tests/predict/test_predict.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../anaconda3/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/predict/test_predict.py:1: in <module>
    import dspy
E   ModuleNotFoundError: No module named 'dspy'
```

This could totally be wrong with how I understand local python builds or some other mistake. Regardless, there should be a little section in the readme about how to run the tests, and get the env setup locally for development

### PR DESCRIPTION
**Pull request by isaacbmiller**
1. Create a new action to run the tests that @thomasahle implemented. Fix #456 
2. Fix the pre-commit checks workflow
3. Adjusted the pyproject.toml to have pytest as a dependency.

Note: databricks integration does not pass tests. Commented out as that is the only integration to do so. To be added back at a later date

### CODE REVIEW

**Comment by okhat** [comment]
The databricks integration is very new so it doesn’t have users yet (merged today). Is unmerging it temporarily useful for this

**Comment by isaacbmiller** [comment]
Yes unmerging would unblock this

**Comment by isaacbmiller** [comment]
Also how do you feel about the pre-commit checks? A lot of the code isn't up to style, and it seems very strict. But this could be the start of actually requiring people's code to meet the style guide

**Comment by okhat** [comment]
Imo let’s not worry about style checks just yet

**Comment by okhat** [comment]
And 100% feel free to temporarily remove the databricks integration if you like. We’ll add it back soon

**Comment by okhat** [comment]
I’d like to merge this when you think it’s ready! No rush though

**Comment by okhat** [comment]
Oh looks like import pydantic is failing here. Btw so far I've been relying on setup.py so it's very possible the *.toml is not completely correct, someone created it a while back and it may have some mistakes

**Comment by isaacbmiller** [comment]
Yeah weird i already manually added pydantic to the .toml file

**Comment by isaacbmiller** [comment]
Ready to merge whenever @okhat

We do have 3 different build systems currently and should probably get rid of 2 of them, but that can be further discussion

**Comment by isaacbmiller** [comment]
Wait don't merge setup.py is broken now

**Comment by isaacbmiller** [comment]
Ok we good now, setup.py build works

**Comment by insop** [comment]
@isaacbmiller , this is great.
I did not go through databrick file since it is commented out, but others looks good to me.

**Comment by isaacbmiller** [comment]
@okhat I am locking pydantic dependency to 2.5.0 because there is a test that specifically relies on the version of pydantic. I would rather merge this than rewrite that test, so I will rewrite the test later

**Comment by isaacbmiller** [comment]
@okhat Can I merge?

**Comment by arnavsinghvi11** [comment]
Hi @isaacbmiller , I just patched the databricks.py file in this latest [PR](https://github.com/stanfordnlp/dspy/pull/470) to move the OpenAI dependency within a local function. feel free to check it out if that passes the tests now so we can merge that alongside this PR!

**Comment by arnavsinghvi11** [comment]
Thanks @isaacbmiller ! ready to merge on @okhat 's go :)

**Comment by okhat** [comment]
Ok running some checks!

**Comment by okhat** [comment]
Unclear why the first test is failing... I tinkered with poetry but it didn't help

**Pull request merged**
