### PR TITLE
DSPy-Clarifai integration - modified example notebook

### PR DESCRIPTION
**Pull request by mogith-pn**
Objective :
1. Modified notebook example with 2 more models.

### CODE REVIEW

**Comment by mogith-pn** [comment]
@CShorten Could you please check this PR ?
TIA :)

**Comment by mogith-pn** [comment]
Hi @okhat ,
Could you please review this PR ?
TIA :)

**Comment by mogith-pn** [comment]
@okhat @arnavsinghvi11 
Could you please take a look at this PR ? 
TIA :)

**Comment by okhat** [comment]
Sorry we missed this for so long @mogith-pn !

**Comment by mogith-pn** [comment]
Thanks @okhat !

**Pull request merged**
