### PR TITLE
merge

### PR DESCRIPTION
**Pull request by sam-h-bean**
merge main

### CODE REVIEW

**Comment by sam-h-bean** [comment]
@okhat took a shot at getting the branch for finetuning 3.5 ready for merging.

**Comment by sam-h-bean** [comment]
Screenshot 2023-11-05 at 6 08 18 PM
I seem to be able to train from this branch now but I have to specify some args like so 
```python
teleprompter = BootstrapFinetune(metric=validate_context_and_answer, provider="openai", multitask=False)
compiled_rag = teleprompter.compile(RAG(), trainset=trainset, target="gpt-3.5-turbo")
```

**Comment by okhat** [comment]
Thanks a ton Sam!

QQ: do we need to have all the cache file changes? So many!

**Comment by okhat** [comment]
@arnavsinghvi11 Could you review the comments on pull #94 and this one and maybe open a PR without the tons of cache changes here?

**Comment by sam-h-bean** [comment]
@okhat I think those cache changes are in main so they need to get into this branch one way or another... I think another option is to just perform the merge directly on the original feature branch

**Comment by sam-h-bean** [comment]
> Hey @sam-h-bean, I've cleaned up the comments on #94. Would it be easier for you to add your changes directly to that branch? While I can add your changes from [this commit](https://github.com/stanfordnlp/dspy/pull/208/commits/1bee90d372af2a1013469d1402cffb2f6d8d7e7e), it's a bit hard to review any other significant changes with all the cache files included in your first merge commit. If there are any, feel free to modify the #94 PR directly! Let me know if you have any questions and when the final changes are ready for review!
> 
> (Btw if there are no additional changes beyond the mentioned commit, happy to merge your changes directly as well. just wanted to check with you before directly merging these changes!)

@arnavsinghvi11 I closed this PR but I took a look at #94 and it does seem like that merge was broken you seem to be missing this loop that is in main 
https://github.com/stanfordnlp/dspy/blob/main/dspy/teleprompt/finetune.py#L73

I can cherry pick my changes out I suppose...

**Pull request closed without merging**
