### PR TITLE
env var for cache_utils.py

### PR DESCRIPTION
**Pull request by JPonsa**
add environmental variable ''DPS_CACHEBOOL' to activate or deactivate cache. By default True.

### CODE REVIEW

**Comment by JPonsa** [comment]
However, it would be cleaner to have config option to disable cache per request

**Comment by insop** [comment]
Thank you very much, I needed this, too.

**Comment by insop** [comment]
@okhat

**Comment by JPonsa** [comment]
@insop is there any action from my side?

**Comment by okhat** [comment]
Not sure why the checks had failed. Rerunning them and will merge if all is good.

Update: OK they're failing again looks like....

**Comment by okhat** [comment]
@isaacbmiller do you happen to know if this failure is expected?

**Comment by isaacbmiller** [comment]
@JPonsa merge main back into your branch and then the checks will pass

@okhat if PRs were created in the ~1 week period where I broke CI from forks, then the tests will fail

**Comment by isaacbmiller** [comment]
CI working as intended

**Pull request merged**
