### PR TITLE
Update hf.py

### PR DESCRIPTION
**Pull request by pminervini**

### CODE REVIEW

**Comment by pminervini** [comment]
This should fix https://github.com/stanfordnlp/dspy/issues/969, checking now

**Comment by pminervini** [comment]
similar fix for another project: https://github.com/EleutherAI/lm-evaluation-harness/pull/1418

**Comment by pminervini** [comment]
Stack trace from a collaborator: 
Screenshot 2024-05-23 at 10 45 54

**Comment by okhat** [comment]
ah ok there's a ruff failure, mind checking?

**Comment by tom-doerr** [comment]
Closes https://github.com/stanfordnlp/dspy/issues/969 and https://github.com/stanfordnlp/dspy/issues/306

**Comment by okhat** [comment]
I'd love to merge this but I still see ruff failures. Lmk if you're able to look into it @pminervini or if someone on our end should. Thanks a ton!

**Comment by arnavsinghvi11** [comment]
Merged, thanks @pminervini !

**Comment by pminervini** [comment]
sorry for being sloppy etc., I was swamped with work  😅

**Pull request merged**
