### PR TITLE
feat(retrieve): add support for faiss retriever, update setup.md, docs

### PR DESCRIPTION
**Pull request by jagane**
Please note that this Pull Request is just an update to the top of the tree and was already discussed in PR #423

### CODE REVIEW

**Comment by insop** [comment]
Thank you.
You could just merge/rebase the branch from PR #439 instead.

**Comment by jagane** [comment]
Hello @insop - Ahh, yes. I could've done that. I will do that next time.
This time, github encouraged me to discard my changes and pull from master.
I did that, then put my changes back in and tested it, so the new PR #440
is a good patch. Go ahead and merge it in, if you don't mind.

Thanks
Jagane

**Comment by insop** [comment]
@okhat , PTAL.

**Comment by okhat** [comment]
Thanks so much! Looks great

**Pull request merged**
