### PR TITLE
Add RunLLM chat widget

### PR DESCRIPTION
**Pull request by cw75**
This PR adds the RunLLM AI chat widget to DSPy's docs page.

### CODE REVIEW

**Comment by cw75** [comment]
Hi @okhat , this is the PR that enables the chat widget. Does the repo have docs preview functionality (in the form of a GitHub action) so we can make sure things are working before merging? Also, once it's merged, will the docs site get updated automatically?

**Comment by okhat** [comment]
adding the docs owner @krypticmouse

**Comment by krypticmouse** [comment]
@cw75 From what I'm seeing RunLLM is in private beta and is it a free utility to run?

**Comment by cw75** [comment]
@krypticmouse yes, we are offering it for free to the DSPy community. Once merged, I can add you and Omar to our admin console so you can see what questions people are asking as well. We've tested docusarous sites locally and it should work.

**Comment by krypticmouse** [comment]
@cw75 Thank you so much for this! Merging this PR and making the docs live now too!

Really appreciate it :slightly_smiling_face: :raised_hands:

**Comment by krypticmouse** [comment]
@arnavsinghvi11 ruff fails but shouldn't be cuz of this PR. I'll fix this later!

**Pull request merged**
