### PR TITLE
Add the ability to set model kwargs for HF local models

### PR DESCRIPTION
**Pull request by bendavidsteel**
Specifically I need this to allow setting the torch dtype so I can load models that only just fit in my VRAM. Let me know if any extra tweaks are required!

### CODE REVIEW

**Comment by EngSalem** [comment]
Is this commit merged to the main branch?
I am looking into loading the HF model with float16 quantization, but it seems that this part isn't merged yet

**Comment by arnavsinghvi11** [comment]
Hi @bendavidsteel just following up on old PRs. can you resolve merge conflicts and lmk when ready to merge? Thanks!

**Comment by bendavidsteel** [comment]
@arnavsinghvi11 resolved!:)

**Comment by arnavsinghvi11** [comment]
Thanks @bendavidsteel !

**Pull request merged**
