### PR TITLE
Debugging Issue #1386

### PR DESCRIPTION
**Pull request by CShorten**
Adds save_field_meta default to `Retrieve`, debugging issue #1386.

### CODE REVIEW

**Comment by isaacbmiller** [comment]
There is also `RetrieveThenRerank` in retrieve.py

**Comment by isaacbmiller** [comment]
Would it be possible to add a test that runs this code and maybe checks that the field info that you want is properly saved?
```python
import dspy

class DumpStateRepro(dspy.Module):
    def __init__(self):
        self.retrieve = dspy.Retrieve(k=1)
        self.predictor = dspy.Predict("question -> answer")

answer_generator = DumpStateRepro()

answer_generator.save("DumpStateRepro", save_field_meta=True)
answer_generator.save("DumpStateRepro", save_field_meta=False)
```

**Comment by CShorten** [comment]
Ok, I think this will fix it, and I like the `save_verbose` naming going forward for consistency / future work on how much optimized program state should be serialized. @isaacbmiller

**Comment by isaacbmiller** [comment]
I do not have time to look at it today. Just merging is fine then

**Comment by CShorten** [comment]
Ok cool, maybe we just add this to `/tests/modules/test_module.py` ?

```python
import dspy

def test_save_method():
    class DumpStateRepro(dspy.Module):
        def __init__(self):
            self.retrieve = dspy.Retrieve(k=1)
            self.predictor = dspy.Predict("question -> answer")

    answer_generator = DumpStateRepro()
    
    answer_generator.save("DumpStateRepro", save_field_meta=True)
    answer_generator.save("DumpStateRepro", save_field_meta=False)
```

**Pull request merged**
