### PR TITLE
feat(dspy): add support for azure ai search

### PR DESCRIPTION
**Pull request by HARISHKUMAR1112001**
**Feature Addition: Introducing AzureAISearchRM Class**

This pull request introduces the AzureAISearchRM class, designed as a retrieval module utilizing Azure AI Search to retrieve top passages for a given query. Below are the details of this new class:

Key Features:

Integration with Azure AI Search: The class enables seamless integration with Azure AI Search service, facilitating the retrieval of top passages based on user queries.

Flexible Configuration: Users can configure various parameters such as the Azure AI Search service name, API key, search index name, and other optional settings like semantic ranking, filter queries, and speller mode.

Ease of Use: The class provides an intuitive interface for interacting with Azure AI Search, making it straightforward for developers to incorporate search functionalities into their applications.

Checks:

- [x] Pre-Commit checks are passing (locally and remotely)
- [x] Title of your PR / MR corresponds to the required format
- [x] Commit message follows required format {label}(dspy): {message}

### CODE REVIEW

**Review by insop — CHANGES_REQUESTED** [review]
Please review my comment and let us know.

**Comment by HARISHKUMAR1112001** [comment]
Thanks @insop for the review.

Yes, Azure has updated their service name from Azure Cognitive Search to Azure AI Search. That's why I kept the name to reflect the current Azure service names.

The code is similar to the dsp module but not identical. In the new updated file, AzureAISeachRM is a subclass of the Retrieval class where we provide support for multiple queries and utilize different methods of the Retrieval class. Additionally, the PR supports full-text search and semantic search along with semantic reranker configurations.

**Comment by insop** [comment]
@HARISHKUMAR1112001 
Thank you for your description.

I reviewed two files again, and there are still lot of common code.
However, if you still think that Azure AI search needs to be a separate file, instead of updating an exiting file.

Then here is what I incline to think:

1. deprecate/remove `dsp/modules/azurecognitivesearch.py` and `docs/api/retrieval_model_clients/AzureCognitiveSearch.md` and properly document the reason of the deprecation
2. then add this file
3. add the retriever document `docs/api/retrieval_model_clients`

**Review by insop — CHANGES_REQUESTED** [review]
Please check the comment.

**Comment by HARISHKUMAR1112001** [comment]
@insop sure will delete the old one and add the doc for new one. Thanks for review..

**Comment by Harish-Tricon** [comment]
@insop , Thank You for your quick review and suggestions. I have updated the PR with all your suggestions. Please have a look once. If anything else required then please let me know.

**Comment by HARISHKUMAR1112001** [comment]
@insop , Thank You for your quick review and suggestions. I have updated the PR with all your suggestions. Please have a look once. If anything else required then please let me know.

**Comment by arnavsinghvi11** [comment]
Hi @HARISHKUMAR1112001 , looks good to merge after you run `"ruff check . --fix-only"`. Thanks!

**Comment by HARISHKUMAR1112001** [comment]
Thank @arnavsinghvi11 , for a quick review, will resolve the issues and update the PR.

**Comment by HARISHKUMAR1112001** [comment]
@arnavsinghvi11 , @insop : resolved all the lint issues.  Please take a look once. Thank You.

**Comment by arnavsinghvi11** [comment]
Thanks @HARISHKUMAR1112001 for your contributions!

**Comment by Harish-Tricon** [comment]
Thanks @insop @arnavsinghvi11  for your quick review and feedbacks.

**Comment by HARISHKUMAR1112001** [comment]
Thanks @insop @arnavsinghvi11 for your quick review and feedbacks.

**Pull request merged**
