### PR TITLE
added gsm8k import to init

### PR DESCRIPTION
**Pull request by aabhi02**
This PR solve the issue #1227

### CODE REVIEW

**Comment by okhat** [comment]
I don't understand the goal of this PR. What are the problems it's fixing?

**Comment by aabhi02** [comment]
The main issue i was facing is as mentioned in #1227 , all the other datasets can be used by imported as `from dspy.datasets` but to use `gsm8k` we have to do `from dspy.datasets.gsm8k import GSM8K`.

and also i want to know what is the reason behind GSM8K not being the child class of `Dataset` class.

If i try to make the `GSM8K` class as the child class of `Dataset` class i am facing the error as shown in #1229

**Comment by okhat** [comment]
Thank you @aabhi02 ! I would close this for now. GSM8K has a metric and other special functions so we want importing it to be a little different for now.

**Comment by aabhi02** [comment]
okay got it. Thanks!

**Pull request closed without merging**
