### PR TITLE
Deprecate old logging

### PR DESCRIPTION
**Pull request by KCaverly**
Deprecate the 'log_openai_usage' configuration option.
As we are now moving to proper logging, we now log all usage by default, and allow the user to specify how they want to handle the logs themselves.

This removes the setting, and all mentions of this settings across gpt3/anthropic/azure_openai/groq.

### CODE REVIEW

**Comment by okhat** [comment]
hey this sounds good (didn't check the code yet) but qq @KCaverly : is logging now expected to print out every HTTP request to OpenAI when using DSPy? that's a bit overkill

**Comment by KCaverly** [comment]
The change is simply moving all the logs that were routing to the .log files before to logging regardless of the configuration setting. This may be overkill to log all the time, it may be a good idea to move these to debug, so they wouldnt clutter up most useful logs.

**Comment by okhat** [comment]
Ah @KCaverly that's not what I meant to ask. I'm saying that right now for some reason logs print every HTTP request to OpenAI to console that's too much logging going on

**Comment by KCaverly** [comment]
Thats odd - I dont think that should be because of this, let me take a look.

**Comment by KCaverly** [comment]
I just took a look, we honestly arent logging that much from the open ai side at all. I just gave it a run, and for rate limiting, I see a ton of messages. This is not due to dspy though, the default logger for 'backoff' the package openai uses for retries, is defaulting to 'info'. 

As such, when we set the previous log level to info globally with the `logging.basicConfig` call, all those get filtered through. Kinda painful, but you can silence them with: 

```
logging.getLogger("backoff").setLevel(logging.WARNING)
```

**Comment by KCaverly** [comment]
As this removes all default log handling from dspy, I've added a helper:

`dspy.show_logging()` which will set a default logger for people.

I made this helper silence the overeager backoff logger aswell.

**Comment by okhat** [comment]
Hmm @KCaverly I merged this but I suspect it turned off most/all INFO logging by accident?

**Comment by okhat** [comment]
When I run BootstrapFewShot I see no logs at all now iiuc

**Comment by KCaverly** [comment]
@okhat that is correct. Its not best practice for a framework to define how applications should show their logs, we had a few issues posted about this. 

To help, I added a helper, ‘dspy.show_logging()’

**Pull request merged**
