### PR TITLE
feature(dspy): return metadata along long_text for ChromaDB retrieval

### LINKED ISSUE #364: Retrieve should enable return of "things" other than passages
The retrieveEnsemble method focusses only on the long_text key. It ignores any other keys provided along with long_text key. I have a custom retriever that returns some metadata along with long_text. retrieveEnsemble should "pass through" this metadata all the way till self.retrieve(question). I mean self.retrieve(question) should return an object that has both passages and metadata keys. While passages can be used to provide the context to the LLM, metadata can be used by the consumer in whichever way he wants to. 

Is there a way to achieve this other than overriding the retrieveEnsemble method?

### PR DESCRIPTION
**Pull request by domci**
Returning metadata along long_text for ChromaDB.
Fixes #364 for ChromaDB

### CODE REVIEW

**Comment by insop** [comment]
Thank you.
It'd be great if you update the document with this change `docs/api/retrieval_model_clients/ChromadbRM.md`

**Comment by domci** [comment]
> docs/api/ret

done! thanks @insop for pointing this out.

**Comment by insop** [comment]
Looks great, thank you.

**Comment by arnavsinghvi11** [comment]
Thanks @domci !

**Pull request merged**
