### PR TITLE
Add the cohere client name to Cohere calls 

### PR DESCRIPTION
**Pull request by BeatrixCohere**

### CODE REVIEW

**Comment by arnavsinghvi11** [comment]
Hi @BeatrixCohere , why is the `client_name=dspy` needed? I have not used Cohere myself, but curious where this client_name is getting used.

**Comment by BeatrixCohere** [comment]
> Hi @BeatrixCohere , why is the `client_name=dspy` needed? I have not used Cohere myself, but curious where this client_name is getting used.

Hi, thanks for reviewing. It aids in debugging issues with the dspy integration with Cohere.

**Comment by jalammar** [comment]
@arnavsinghvi11 This change would help prioritize DSPy at Cohere and contribute to how the models may work in the future to support its use cases.

**Comment by arnavsinghvi11** [comment]
Merged. thanks @BeatrixCohere !

**Pull request merged**
