### PR TITLE
add OpenAICompatible

### PR DESCRIPTION
**Pull request by SomeoneKong**
Add OpenAICompatible, likes GPT3, but each instance uses a separate cache.

Allow to use multi OpenAICompatible LLM service with different base_url

related #744, #915

### CODE REVIEW

**Comment by arnavsinghvi11** [comment]
Hi @SomeoneKong , thanks for the PR! looks good and helps resolve the issues. Could we refactor this class to be `dspy.MultiOpenAI` to help distinguish from the existing `dspy.OpenAI` while highlighting the use case for supporting configuring multiple open ai clients while using this?

It would also be great if you could add documentation for this class as done for the LMs in [our documentation here?](https://github.com/stanfordnlp/dspy/tree/main/docs/api/language_model_clients), detailing a working example of configuring 2 OpenAI SDK clients using this. Thanks!

**Comment by SomeoneKong** [comment]
@arnavsinghvi11 done

**Comment by SomeoneKong** [comment]
Please note:
If it is used for multiple instances with different base_url, it only works with openai>=1.0 dependency.
When using only one base_url, this implementation is also compatible with openai <1.0.

Therefore, I previously named it OpenAICompatible.

**Comment by arnavsinghvi11** [comment]
Thanks @SomeoneKong !

**Pull request merged**
