### PR TITLE
feat: adds Cloudflare Workers AI

### PR DESCRIPTION
**Pull request by isbecker**
This feature adds support for using [Cloudflare Workers AI](https://developers.cloudflare.com/workers-ai/).
Using Cloudflare gives support for a wide variety of open source [models](https://developers.cloudflare.com/workers-ai/models/#text-generation).

#### env variables
`CLOUDFLARE_ACCOUNT_ID`
`CLOUDFLARE_API_KEY`

```python
lm = dspy.CloudflareAI(model="@cf/meta/llama-3-8b-instruct", 
          account_id="", # optional, will check env
          api_key="" # optional, will check env
)
dspy.settings.configure(lm=lm)
# ...use normally...
```

### CODE REVIEW

**Comment by arnavsinghvi11** [comment]
Hi @isbecker , thanks for the PR!

Could you also add documentation for the CloudfareAI LM to provide context as done for the LMs in [our documentation here?](https://github.com/stanfordnlp/dspy/tree/main/docs/api/language_model_clients)? 

Also, could you please rebase and merge this branch with the latest version on main? Seems like there was a failing test on our end (nothing wrong with this PR) that just needs an update. Ready to merge after that!

**Comment by isbecker** [comment]
Will do both, I'm away from computer today, but I will have time tomorrow to make those changes 🙂

**Comment by isbecker** [comment]
@arnavsinghvi11 looks good?

- [x] tests pass locally
- [x] docs added

**Comment by arnavsinghvi11** [comment]
Thanks @isbecker !

**Pull request merged**
