### PR TITLE
fix for weaviate outdated client version. Issue 699

### PR DESCRIPTION
**Pull request by jettro**
I upgraded the client version in the poetry project configuration. I changed the contract of the init method to pass a few additional parameters important for configuring the hybrid query. 

I did not commit the poetry.lock file, as this is giving regular merge problems. I hope that is done before creating a release.

### CODE REVIEW

**Comment by jettro** [comment]
Needs a small update, will fix it asap

**Comment by arnavsinghvi11** [comment]
Hi @jettro , thanks for the updates. Can you run `'ruff check . --fix-only` to fix the failing CI test. 

Also it's failing the dependency tests: 

```
Warning: poetry.lock is not consistent with pyproject.toml. You may be getting improper dependencies. Run `poetry lock [--no-update]` to fix it.

Because dspy depends on weaviate-client (^4.5.4) which doesn't match any versions, version solving failed.

Could you rerun this as well

**Comment by jettro** [comment]
@arnavsinghvi11 Done, added the lock file, and ran the ruff command.

**Comment by arnavsinghvi11** [comment]
Thanks @jettro !

**Pull request merged**
