### PR TITLE
Update FAQ to mention `DSP_CACHEDIR` for local cache.

### PR DESCRIPTION
**Pull request by tom-doerr**

### CODE REVIEW

**Comment by okhat** [comment]
This is good but it will cause people to set both paths to the sane string….

**Comment by arnavsinghvi11** [comment]
Hi @tom-doerr , was this resolved and ready to merge?

**Comment by tom-doerr** [comment]
Yes I think it should be clearer now

**Comment by arnavsinghvi11** [comment]
Thanks @tom-doerr !

**Pull request merged**
