### PR TITLE
Fix applymap deprecation warning

### LINKED ISSUE #492: FutureWarning: DataFrame.applymap has been deprecated
Using `pandas==2.1.4` I get the warning
```
dspy/evaluate/evaluate.py:143: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(truncate_cell)
```
each time I use dspy.

### PR DESCRIPTION
**Pull request by quajak**
Fixes #492

### CODE REVIEW

**Comment by insop** [comment]
Super, thank you!

**Comment by okhat** [comment]
Hey @isaacbmiller do you know why things are failing here, it's too small of a change to cause failing checks

**Comment by isaacbmiller** [comment]
Yes, it is because #565 Needs to be merged

**Comment by isaacbmiller** [comment]
Merge main and the tests should pass!

**Comment by maxfriedrich** [comment]
After this change I'm getting `'DataFrame' object has no attribute 'map'` on Google Colab where Pandas 1.5.3 is installed by default, should dspy require a newer Pandas version?

**Pull request merged**
