### PR TITLE
[Bug Fix] WeaviateRM

### PR DESCRIPTION
**Pull request by CShorten**
This should fix it, accidentally wrapped the return in a `dspy.Prediction`.

Sorry for the back and forth with this, pretty sure it is in good shape now.

### CODE REVIEW

**Comment by CShorten** [comment]
Hey @okhat, thanks for taking a look! I tested the currently 2.1.6 build and it is still looking for the `long_text` key, I think because the call to `dspy.Prediction` wraps passages in something else. I am basing these changes off of the Clarifai integration, which seems to work in the notebook (although it is not 100% clear if that was from importing the current dspy-ai package or a local build).

However, I can confirm 100% that the current WeaviateRM doesn't work.

**Comment by CShorten** [comment]
@DanielUH2019 would you be interested in testing the PineconeRM and maybe uploading an example notebook to /examples/Integrations?

**Comment by CShorten** [comment]
Maybe worth noting the ChromadbRM also returns passages directly - https://github.com/stanfordnlp/dspy/blob/main/dspy/retrieve/chromadb_rm.py

**Comment by okhat** [comment]
Yeah a Prediction is better because you can return other fields too later

**Comment by CShorten** [comment]
Ah indeed, that would be more powerful. Would it still be an idea to patch it for now with this -- and then going forward remove how `dsp.retrieveEnsemble` parses the `long_text` key?

**Comment by DanielUH2019** [comment]
> @DanielUH2019 would you be interested in testing the PineconeRM and maybe uploading an example notebook to /examples/Integrations?

Hi @CShorten, thanks for reaching out! I will try to do it this weekend

**Pull request merged**
