### PR TITLE
Restructure navigation and update documentation

### PR DESCRIPTION
**Pull request by ammirsm**
This pull request includes several updates to the documentation and configuration of the DSPy project. The most significant changes involve the addition of new community resources, restructuring of the documentation, and updates to dependencies.

### Documentation Updates:

* [`docs/docs/community/community-resources.md`](diffhunk://#diff-1349058c86ef1ed3f214e676626c6139a2698231a6835581d48cee9db413dc31R1-R56): Added a comprehensive list of tutorials, blogs, videos, and podcasts related to DSPy. This includes various links to external resources and a call for community contributions.

* [`docs/docs/community/how-to-contribute.md`](diffhunk://#diff-68b8039d71781a860fa26e8bf15549572ad0cbe9a8cc119b56da82c6f9bb66c0R1-R12): Added a section on development setup and contribution guidelines, encouraging community members to contribute modules or optimizers and providing links to walkthroughs for adding custom language model clients.

* [`docs/docs/community/use-cases.md`](diffhunk://#diff-97d10894e75c2c6cbfdcb0543f3b4915b7b9efafba4dcb27688deeaba7356eb9R1-R107): Created a new document listing various use cases of DSPy in companies and research papers, as well as repositories using DSPy. This aims to showcase practical applications and encourage community contributions.

* [`docs/mkdocs.yml`](diffhunk://#diff-7618337a88ea47f9b778a21f0e17d43eab2aba4880c6be2d95a7bf95e4b8b2dfL9-R58): Restructured the navigation to improve the organization of the documentation. This includes changes to the sidebar and the addition of new sections such as "Community" and "Components." [[1]](diffhunk://#diff-7618337a88ea47f9b778a21f0e17d43eab2aba4880c6be2d95a7bf95e4b8b2dfL9-R58) [[2]](diffhunk://#diff-7618337a88ea47f9b778a21f0e17d43eab2aba4880c6be2d95a7bf95e4b8b2dfL84-R101)

### Dependency Updates:

* [`pyproject.toml`](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L45-R45): Removed the `json-repair` dependency from the project dependencies list. [[1]](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L45-R45) [[2]](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L139-R138)This pull request includes extensive updates to the documentation of DSPy, focusing on improving the organization and adding new sections for better clarity and usability. The main changes include the addition of new guides, restructuring of the navigation, and updates to community resources.

Documentation Enhancements:

* [`docs/docs/community/development-setup.md`](diffhunk://#diff-e299b5343fc47ed0220ab8b4afdbbd419723a18899d5665b40bf24781f44c2e9R1-R3): Added a new section for development setup instructions.
* [`docs/docs/community/how-to-contribute.md`](diffhunk://#diff-68b8039d71781a860fa26e8bf15549572ad0cbe9a8cc119b56da82c6f9bb66c0R1-R7): Added a new section on contributing, including guidelines for adding new modules or optimizers and setting up custom LM and RM clients.
* [`docs/docs/community/related-projects.md`](diffhunk://#diff-54f19047da833cd6cb39955c00136ebe4ad0f0a1f6f9f52143c8d7104e4e06ceR1-R107): Added a comprehensive list of use cases, papers, repositories, and integrations related to DSPy.
* [`docs/docs/community/tutorials.md`](diffhunk://#diff-c07475ecb962566a3a6c3d9effbdaa20844ab0f219c9b9bcf069f2ff1f179d32R1-R56): Added a new section listing tutorials and blog posts on DSPy, including blogs, videos, and podcasts.
* [`docs/docs/tutorials/debugging.md`](diffhunk://#diff-c94bb3dc229ea6892299bdfe451cad6ec1913ae60dad901d920705d225060c4dR1-R51): Added a new debugging guide to help users troubleshoot common issues with DSPy programs.

Navigation and Structural Changes:

* [`docs/mkdocs.yml`](diffhunk://#diff-7618337a88ea47f9b778a21f0e17d43eab2aba4880c6be2d95a7bf95e4b8b2dfL9-R59): Restructured the navigation to improve the organization of the documentation, including renaming and reordering sections, and adding new community resources and debugging sections. [[1]](diffhunk://#diff-7618337a88ea47f9b778a21f0e17d43eab2aba4880c6be2d95a7bf95e4b8b2dfL9-R59) [[2]](diffhunk://#diff-7618337a88ea47f9b778a21f0e17d43eab2aba4880c6be2d95a7bf95e4b8b2dfR85-R103) [[3]](diffhunk://#diff-7618337a88ea47f9b778a21f0e17d43eab2aba4880c6be2d95a7bf95e4b8b2dfR198-R199) [[4]](diffhunk://#diff-7618337a88ea47f9b778a21f0e17d43eab2aba4880c6be2d95a7bf95e4b8b2dfR247)

Minor Adjustments:

* [`docs/docs/faqs.md`](diffhunk://#diff-c692537c6f29881be49c3b65ef04e4b03394bd9a3c99e01013dd3ad62c476fcaL168-L175): Removed redundant contributing information.
* [`docs/docs/intro.md`](diffhunk://#diff-5ddf6bcf52fe8ef8dfc865f5f2295616d5c073d899766372e5929cc0fd479ffdR3-R9): Updated the intro file to hide the table of contents and navigation.

[ Copilot generated ]

### CODE REVIEW

**Comment by okhat** [comment]
Thanks a ton Amir! Are we linking to some files that don't exist, i.e. is this a "draft"?

For example, we link to debugging.md

**Comment by ammirsm** [comment]
> Thanks a ton Amir! Are we linking to some files that don't exist, i.e. is this a "draft"?
> 
> For example, we link to debugging.md

Yes, sir. I'm adding some placeholders, and if you think that's sufficient and the structure is good, we'll fill them up. We'll then restructure the actual files to make them tidy and push the first version of this structure up. I wanted to keep the first version of the PR simple to make it easier to review.

**Comment by sushmanthreddy** [comment]
@ammirsm the redirects are kept for a reason because those links are used in different websites ,which are giving 404 error. It was creating lot of confusion when user were accessing them .


for example this below link have found it on some website of vector database ,which isn't accessible,because the file name has changed to 2-signatures and it is not accessible




https://dspy-docs.vercel.app/docs/building-blocks/signatures


@okhat the redirects shouldn't be removed for other columns  also

**Comment by okhat** [comment]
@sushmanthreddy Yes good point we want the redirects as long as they're correct

**Pull request merged**
