### PR TITLE
linter: black & isort for auto-formatting on PRs

### PR DESCRIPTION
**Pull request by lawliet19189**

### CODE REVIEW

**Comment by okhat** [comment]
What's needed for this to be merged? What are the downsides of merging it? Will it complicate the workflow?

**Comment by piotrlaczkowski** [comment]
I would not split this into separate parts but rather package it all into a dedicated pre-commit + related worflow (which will help much better locally before doing PRs) -> I can set this up.

**Comment by okhat** [comment]
@piotrlaczkowski I invited you to the repo! Please feel free to merge this when you feel it's at a good stage!

**Comment by piotrlaczkowski** [comment]
@okhat I still have 403 upon the push for my new branch, just tested.

**Comment by piotrlaczkowski** [comment]
I think we can close this one (both tools are already present in the pre commit.

**Pull request closed without merging**
