### PR TITLE
Fix: Add logging path modification for OpenAI usage

### PR DESCRIPTION
**Pull request by neil-sola**
This is to ensure that extraneous files are created in specified folder.

Refer to #211

### CODE REVIEW

**Comment by neil-sola** [comment]
Hmm, I see. What are your opinions of using an env_var here: either to prefix the logging files to a specific folder, or to enable/disable?

I was thinking maybe something like `DSPY_LOGGING_DIR` to prefix a folder to save logs, or `DSPY_LOGGING` to enable/disable logging.

**Comment by neil-sola** [comment]
@okhat I updated the PR to focus on just giving the user the ability to specify a folder to save logs to — the mechanism to allow enabling/disabling of logging seems more complicated, but this should provide some level on configurability on where logs are stored.

**Comment by KCaverly** [comment]
I've added an initial global logger, with configuration here: #684.
Does the API offered in that PR, cover all the uses outlined here?

**Comment by neild0** [comment]
> I've added an initial global logger, with configuration here: #684. Does the API offered in that PR, cover all the uses outlined here?

Yup, looks perfect — thanks so much!

**Pull request closed without merging**
