### PR TITLE
added Databricks integrations for DSPy LMs/RM configurations

### PR DESCRIPTION
**Pull request by arnavsinghvi11**
integrated Databricks connectors for configuring LMs and RM in DSPy.

LMs - adapted from OpenAI Client SDK in [Databricks Model Serving endpoints](https://docs.databricks.com/en/machine-learning/model-serving/score-model-serving-endpoints.html#language-OpenAI%C2%A0client)
Supports chat, completions, and embeddings model formats.

RM - adapted from [querying Databricks Vector Search Endpoint](https://docs.databricks.com/en/generative-ai/create-query-vector-search.html#create-a-vector-search-index)

### CODE REVIEW

**Comment by arnavsing-db** [comment]
Thanks @insop. Added the LM docs. The RM docs are being developed in a background docs development (as the current version is missing most of the Retrievers) so will update the Databricks RM with that outside of this PR as well!

**Comment by arnavsinghvi11** [comment]
Thanks @insop. Added the LM docs. The RM docs are being developed in a background docs development (as the current version is missing most of the Retrievers) so will update the Databricks RM with that outside of this PR as well!

**Comment by insop** [comment]
> Thanks @insop. Added the LM docs. The RM docs are being developed in a background docs development (as the current version is missing most of the Retrievers) so will update the Databricks RM with that outside of this PR as well!

Thank you @arnavsinghvi11, PR looks good to me.

**Comment by okhat** [comment]
Thank you so much @arnavsinghvi11 ! And thanks a lot for the review @insop !

**Pull request merged**
