### PR TITLE
Enhance history with filterable content

### PR DESCRIPTION
**Pull request by Anindyadeep**
This PR adds datetime (standard ISO format and some more parameters) to the history so that it could be easily searchable / filterable. Additionally this PR enhances the inspect_history function by adding the datetime timestamp into it. Which shows like this:

Screenshot 2024-09-30 at 12 06 35 AM

Fixes issue: #1073

### CODE REVIEW

**Comment by okhat** [comment]
This is great, thank you @Anindyadeep ! But if it’s not too much trouble could you keep the format / style of the code — especially not in the same PR that changes functionality.

**Comment by Anindyadeep** [comment]
> This is great, thank you @Anindyadeep ! But if it’s not too much trouble could you keep the format / style of the code — especially not in the same PR that changes functionality.

Hey, so I actually installed pre-commit, I am not sure, that formatting might be caused by that.

**Comment by okhat** [comment]
@Anindyadeep Maybe the pre-commit you have is outdated? It just changed the file a bit too much IMO, it will hurt other WIP merges.

**Comment by okhat** [comment]
@Anindyadeep I would love to merge this and I think the real change is just this one line right?

```python
        entry = dict(
            timestamp=datetime.now().isoformat(),
            uuid=str(uuid.uuid4()),
            model=self.model,
            model_type=self.model_type,
        )
```

Could you make the PR change just this one line if so (plus any required imports and any other changes I missed). If too busy, I can make that change and credit you in a different PR.

**Comment by Anindyadeep** [comment]
> @Anindyadeep I would love to merge this and I think the real change is just this one line right?
> 
> ```python
>         entry = dict(
>             timestamp=datetime.now().isoformat(),
>             uuid=str(uuid.uuid4()),
>             model=self.model,
>             model_type=self.model_type,
>         )
> ```
> 
> Could you make the PR change just this one line if so (plus any required imports and any other changes I missed). If too busy, I can make that change and credit you in a different PR.

Ahh sorry, I missed to add the changes. Let me do it in some time.

**Pull request merged**
