### PR TITLE
Added support for variable sized output vectors via Nomic Embed v1.5

### PR DESCRIPTION
**Pull request by AndriyMulyar**
Added support for Nomic Embed v1.5: https://blog.nomic.ai/posts/nomic-embed-matryoshka

This let's you specify a vectorizer that will generate much smaller but still performant embeddings for local use.

### CODE REVIEW

**Comment by okhat** [comment]
Wonderful, thanks a lot. Merging after checks.

**Comment by okhat** [comment]
Ok we have a small problem:

```python
import nomic
```

I guess normally we deal with this by importing optional dependencies either:
1. Inside the class
2. Outside the class, but in try/except form and on `except` just set it to None or something

**Comment by AndriyMulyar** [comment]
Will update.

**Comment by arnavsinghvi11** [comment]
Hi @AndriyMulyar , just following up on this update. looks good to merge after editing the import. Feel free to use [examples from other retrievers](https://github.com/stanfordnlp/dspy/blob/44f03ce2f92b663de6b8ae3437ebf86998e1e79e/dspy/retrieve/neo4j_rm.py#L17) on how to optionally import the local dependencies

**Pull request closed without merging**
