### PR TITLE
Lancedb Integration

### PR DESCRIPTION
**Pull request by PrashantDixit0**
This PR adds LanceDB as a retriever to handle large datasets.

### CODE REVIEW

**Comment by PrashantDixit0** [comment]
@okhat Please approve the workflow. If any changes are required let me know.

**Comment by CShorten** [comment]
Hey @PrashantDixit0, happy to help with this! 👋 

- Can you please take a look at the conflicts in the poetry setup and let me know what you think?

- It looks like the ruff linter is unhappy with unused variables not related to this PR. @PrashantDixit0 you can fix this with `ruff check . --unsafe-fixes --fix`, cc @isaacbmiller

**Comment by PrashantDixit0** [comment]
@CShorten While running `ruff check . --fix-only` I am getting error

```
error: TOML parse error at line 216, column 1
    |
216 | indent-width = 4
    | ^^^^^^^^^^^^
unknown field `indent-width`, expected one of `allowed-confusables`, `builtins`, `cache-dir`, `dummy-variable-rgx`, `exclude`, `extend`, `extend-exclude`, `extend-include`, `extend-ignore`, `extend-select`, `extend-fixable`, `extend-unfixable`, `external`, `fix`, `fix-only`, `fixable`, `format`, `force-exclude`, `ignore`, `ignore-init-module-imports`, `include`, `line-length`, `tab-size`, `required-version`, `respect-gitignore`, `select`, `show-source`, `show-fixes`, `src`, `namespace-packages`, `target-version`, `task-tags`, `typing-modules`, `unfixable`, `flake8-annotations`, `flake8-bandit`, `flake8-bugbear`, `flake8-builtins`, `flake8-comprehensions`, `flake8-errmsg`, `flake8-quotes`, `flake8-self`, `flake8-tidy-imports`, `flake8-type-checking`, `flake8-gettext`, `flake8-implicit-str-concat`, `flake8-import-conventions`, `flake8-pytest-style`, `flake8-unused-arguments`, `isort`, `mccabe`, `pep8-naming`, `pycodestyle`, `pydocstyle`, `pylint`, `per-file-ignores`, `extend-per-file-ignores`
```

**Comment by CShorten** [comment]
Thanks @PrashantDixit0, maybe for now let's revert the commit of running the linter on all the files. I noticed this when I took a look this morning as well. I'm surprised this changed as many files as it did though, for me it was about ~8 this morning and I was able to manually inspect that it was mostly unused variables, etc. as mentioned in my original comment. 

@isaacbmiller @insop can you please advise us on this?

**Comment by insop** [comment]
> Thanks @PrashantDixit0, maybe for now let's revert the commit of running the linter on all the files. I noticed this when I took a look this morning as well. I'm surprised this changed as many files as it did though, for me it was about ~8 this morning and I was able to manually inspect that it was mostly unused variables, etc. as mentioned in my original comment.
> 
> @isaacbmiller @insop can you please advise us on this?

With @CShorten 's nudge, I went over the change.
I tend to think that if all the changes are related to the PR? many of them look like style changes...

**Comment by PrashantDixit0** [comment]
I'll relock poetry file

**Comment by PrashantDixit0** [comment]
@isaacbmiller @CShorten Done :+1:, Now conflicts are resolved

**Comment by CShorten** [comment]
Thank you so much @isaacbmiller @insop @PrashantDixit0! 🔥 🚀

**Pull request merged**
