### PR TITLE
Easier api for transforming modules with assertions

### PR DESCRIPTION
**Pull request by Shangyint**
Now, it is possible to write `assert_transform_module(module)` to transform a module to handle suggestions and assertions. The default behavior is implemented by the `backtrack_handler`, which automatically backtracks for failing assertions and suggestions.

### CODE REVIEW

**Comment by okhat** [comment]
That’s so cool! Can we also shorten that function’s name?

Or even make it a module method?

program.activate_assertions()

**Comment by Shangyint** [comment]
Great advice! Now we can do:
```python
a = Program()
a.activate_assertions()
# now a can backtrack and self-refine
```
or
```python
teleprompter.compile(student=Program().activate_assertions())
```

**Comment by okhat** [comment]
Amazing! Before I merge,

will this break existing code?

is it an in-place or new-value method? either one is fine just checking

**Review by arnavsinghvi11 — COMMENTED** [review]
`activate_assertions` is nice!

to clarify, `longformqa_with_assertions = assert_transform_module(LongFormQAWithAssertions().map_named_predictors(Retry), backtrack_handler) 
`
would look something like this now? 

`longformqa_with_assertions = LongFormQAWithAssertions().activate_assertions()`

**Comment by Shangyint** [comment]
Yes. And it shouldn't break any existing code! Could you double check both the old and new api works @arnavsinghvi11?

**Comment by okhat** [comment]
Arnav’s answer implies it is NOT in place, just to be sure right?

**Comment by Shangyint** [comment]
Thanks! Pushed a fix. Both should work now

**Comment by arnavsinghvi11** [comment]
Looks good @Shangyint ! Just a small [issue](https://github.com/stanfordnlp/dspy/commit/6407b3667792c384d81d2567bdb09a1a84217678) which relies on this change to be merged for `activate_assertions()` to work.

**Pull request merged**
