### PR TITLE
feat(program_of_thought): added support for custom import whitelist and added dynamic input and output field names for PoT 

### PR DESCRIPTION
**Pull request by Arbaaz-Mahmood**
While, the PythonInterpreter and CodePrompt modules allowed for importing a white_list, this functionality hadn't been made available directly inside ProgramofThought. This was causing repeated hinderance when language models would try to use any math packages that were not allowed like sympy etc, which makes for a bad dev UX.

### CODE REVIEW

**Comment by Arbaaz-Mahmood** [comment]
@okhat Please review. The pytest failure was fixed.

**Comment by okhat** [comment]
Thank you @Arbaaz-Mahmood ! I will tag the author of this class, @arnavsinghvi11

**Comment by arnavsinghvi11** [comment]
Hi @Arbaaz-Mahmood , thanks for this PR! could you run `ruff check . --fix-only` to pass the failing and tests. LGTM otherwise!

**Comment by Arbaaz-Mahmood** [comment]
Hey @arnavsinghvi11 I think this should be good to go. I've applied the ruff fix and deleted the anthropic stuff from this commit.

**Comment by Arbaaz-Mahmood** [comment]
@okhat could you re-run tests on this? I had fixed the failing ruff tests and deleted the anthropic commits from here.

**Comment by arnavsinghvi11** [comment]
Hi @Arbaaz-Mahmood, I still see the changes made to anthropic.py. could you remove this and submit another commit (since there's a separate PR for that #679 )? thanks.

**Comment by Arbaaz-Mahmood** [comment]
moved to #710

**Pull request closed without merging**
