### PR TITLE
Add Support for List[Image]

### PR DESCRIPTION
**Pull request by ryanh-ai**
When providing `List[dspy.Image]` for input field, the `ChatAdapter` was formatting the list of images as a string and overflowing the input context for LM's from multiple providers.

Changes were done very quickly to unblock active work, but this is tested locally across Bedrock and OpenAI providers.

### CODE REVIEW

**Comment by ryanh-ai** [comment]
@isaacbmiller FYI, per Discord thread on this issue

**Comment by okhat** [comment]
Thanks a ton @ryanh-ai ! I guess in general do we need more complex collections of images? Will people also want to do dict[str, list[Image]] and all kinds of crazy things?

If we only wanna support list[Image], then this PR is good.

**Comment by isaacbmiller** [comment]
I think that people will at a minimum want to do things like dict[str, Image] which I am not sure even works currently.

I think this PR shouldn't be merged and I can work on a scalable solution for adapters for all different types including Image

**Comment by ryanh-ai** [comment]
Agree above on the dictionary! 

I also found an edge case when length of image list is 1.  I will update the patch when I adjust that, but not invest too much more in this until you determine best path forward.  I'm happy to test as you do!

**Pull request closed without merging**
